### ISSUE TITLE
Healthcheck for apps fail

### ISSUE THREAD

**Issue by kroese** [worph/casa-img#1]
When running the image, and installing an app from the appstore, I always see that the healthcheck fails (because it seems to connect to 127.0.0.1:port instead of the container IP). When manually navigating to the app, it still works, but its very annoying that the healthcheck always fails. Do you have any clue what could be wrong?

Also, do you plan to keep your submodule projects in sync with the upstream branch? Because right now they are 3 months behind and I am using them for my fork: https://github.com/dockur/casa .

**Comment by worph** [comment]
Thank you for reaching out!

At the moment, I don’t have a definitive answer, but I'll investigate this issue. The health check failure might stem from the way it’s connecting to 127.0.0.1 indeed.

Regarding updates to the submodules, I plan to keep them aligned with the upstream branch. However, the process takes some time as I like to test everything thoroughly before releasing updates. I’ll aim to push a new version soon.

**Comment by worph** [comment]
Hi again,
I updated the submodule and will now follow the release of IceWhaleTech for the gitmodule.
There are actually only three submodules I modified to make the image more "docker image friendly". For the other submodules, I changed to use the upstream from https://github.com/IceWhaleTech directly and fixed their versions to only have stable code (version in the git module):

url = https://github.com/worph/CasaOS-UI.git
url = https://github.com/worph/CasaOS-AppManagement.git
url = https://github.com/worph/CasaOS-UserService.git

About the healthcheck issue, I have trouble reproducing it. Can you give me more context? Logs, the app you try to install from the store, etc?

If you want to discuss more directly, my handle is ascla420_89745 on the IceWhale Discord.

**Comment by worph** [comment]
Thanks to your steps to reproduce, I understand the issue.

As for the update, there’s no fix yet, but I’m working on it.
I’m still pondering how to solve the issue since, as you noticed, it stems from the CasaOS health check service trying to ping the 127.0.0.1 IP instead of the container’s IP. I could modify the health check service to ping the container, but the challenge for me is finding that IP within CasaOS in a clean way (and without modifying CasaOS too much).

**Comment by worph** [comment]
I pushed a fix for the healthcheck issue that maintains the healthcheck functionality while solving the container connectivity problem.
The solution involves creating a network that allows containers to communicate:

```
docker network create casa-net
docker run -it --rm -p 8080:8080 -e REF_NET=casa-net -v /home/example:/DATA -v /var/run/docker.sock:/var/run/docker.sock --stop-timeout 60 dockurr/casa
```

The key change is using REF_NET=casa-net environment variable, which ensures all containers are on the same network when created. This allows proper container-to-container communication for healthchecks.

While disabling the healthcheck was an option, I preferred maintaining this feature while keeping the code clean to avoid conflicts with the IceWhale branch as much as possible.
